SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/dec_proj
SPRING_DATASOURCE_USERNAME=root
SPRING_DATASOURCE_PASSWORD=Aquib9353@
RAZORPAY_KEY_ID=rzp_test_A0pogOFt1fVWQe
RAZORPAY_KEY_SECRET=KMI7TRVgCayp1BvrtWvIQ6X1
